export const suggestions: string[] = [
  "Break",
  "PTI",
  "Pre-Trip Inspection",
  "Post-Trip Inspection",
  "Pickup",
  "Delivery",
  "Pick Co Driver",
  "Drop Co Driver",
  "Waiting",
  // "Loading",
  // "Unloading",
  // "Download",
  "Meal",
  // "Drop & Hook",
  "Fuel",
  "Lunch",
  "Shop",
  // "Driving",
  // "Sleeper",
  "Weight Station",
  "DOT Inspection",
  "Accident"
];
